name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    name: build-and-test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
            7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -p:ContinuousIntegrationBuild=True --no-restore --configuration Release
    - uses: nanasess/setup-chromedriver@v2
    - name: Test
      run: dotnet test ~/IntelliTect.TestTools.Selenate.Tests/IntelliTect.TestTools.Selenate.Tests.csproj --no-build --configuration Release --verbosity normal

  automerge:
    needs: [build-and-test]
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.8.0
