name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    name: build-and-test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
            6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -p:ContinuousIntegrationBuild=True --no-restore --configuration Release
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest
      id: setup-chrome
    - uses: nanasess/setup-chromedriver@v1
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '111.0.5563.6400'
    - name: Install chrome driver on mac/ubuntu
      if: ${{ matrix.os }} != 'windows-latest
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    - name: Install chrome driver on windows
      if: ${{ matrix.os }} == 'windows-latest
      run: chromedriver --url-base=/wd/hub &
    - run: |
        echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
  
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

  automerge:
    needs: [build-and-test]
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.6.2
