name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    name: build-and-test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
            6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -p:ContinuousIntegrationBuild=True --no-restore --configuration Release
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
      id: setup-chrome
    - run: |
        echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
        chrome --version
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
