name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    name: build-and-test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
            7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -p:ContinuousIntegrationBuild=True --no-restore --configuration Release

    - name: Install latest Chrome (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        $ChromeInstallerFile = "googlechromestandaloneenterprise64.msi"
        $ChromeInstallerUrl = "https://dl.google.com/tag/s/dl/chrome/install/${ChromeInstallerFile}"
        $ChromeInstallerPath = Join-Path -Path "${env:Temp}" -ChildPath $ChromeInstallerFile
        (New-Object System.Net.WebClient).DownloadFile($ChromeInstallerUrl, $ChromeInstallerPath)
        Start-Process -FilePath msiexec.exe -ArgumentList "/i $ChromeInstallerPath /QN /norestart" -Wait -PassThru
    - name: Install latest Chrome (Linux)
      if: ${{ runner.os == 'Linux' }}
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install google-chrome-
    - name: Install latest Chrome (macOS)
      if: ${{ runner.os == 'macOS' }}
      run: |
        wget -q https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg
        hdiutil attach -quiet -noautofsck -noautoopen googlechrome.dmg
        sudo cp -r /Volumes/Google\ Chrome/Google\ Chrome.app /

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

  automerge:
    needs: [build-and-test]
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.8.0
